version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=settings_docker
    restart: unless-stopped
