version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: kabaadwala_db
      POSTGRES_USER: kabaadwala_user
      POSTGRES_PASSWORD: kabaadwala_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kabaadwala_user -d kabaadwala_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_files:/app/media
      - static_files:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=kabaadwala_db
      - DB_USER=kabaadwala_user
      - DB_PASSWORD=kabaadwala_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    command: python manage_celery.py worker --loglevel=info
    volumes:
      - .:/app
      - media_files:/app/media
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=kabaadwala_db
      - DB_USER=kabaadwala_user
      - DB_PASSWORD=kabaadwala_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build: .
    command: python manage_celery.py beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=kabaadwala_db
      - DB_USER=kabaadwala_user
      - DB_PASSWORD=kabaadwala_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  flower:
    build: .
    command: python manage_celery.py flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/2
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
  media_files:
  static_files:
