# Generated by Django 5.2.5 on 2025-08-31 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_name_chatroom_product_chatroom_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='flagged_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('order', 'Order'), ('product', 'Product'), ('support', 'Support')], default='product', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatModeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violation_type', models.CharField(choices=[('contact_sharing', 'Contact Information Sharing'), ('external_payment', 'External Payment Request'), ('escrow_bypass', 'Escrow Bypass Attempt'), ('inappropriate', 'Inappropriate Content'), ('spam', 'Spam')], max_length=50)),
                ('detected_content', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('admin_action', models.CharField(blank=True, max_length=100)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='chat.chatmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
