# Generated by Django 5.2.4 on 2025-07-25 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="address_line2",
            new_name="landmark",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="address_line1",
            new_name="recipient_name",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="postal_code",
            new_name="recipient_phone",
        ),
        migrations.RenameField(
            model_name="vendorprofile",
            old_name="gstin",
            new_name="business_phone",
        ),
        migrations.RenameField(
            model_name="vendorprofile",
            old_name="kyc_submitted_at",
            new_name="kyc_approved_at",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="bank_account",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="ifsc_code",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="is_kyc_verified",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="pan_number",
        ),
        migrations.AddField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[("home", "Home"), ("office", "Office"), ("other", "Other")],
                default="home",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="flat_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="pincode",
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="street_address",
            field=models.TextField(default="000000"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="business_email",
            field=models.EmailField(default="none", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="business_hours",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="kyc_rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="store_address",
            field=models.JSONField(default="none"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="store_banner",
            field=models.ImageField(blank=True, null=True, upload_to="store_banners/"),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="store_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="store_logo",
            field=models.ImageField(blank=True, null=True, upload_to="store_logos/"),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="store_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="VendorKYC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pan_document", models.FileField(upload_to="kyc/pan/")),
                ("gstin_document", models.FileField(upload_to="kyc/gstin/")),
                ("bank_account_number", models.CharField(max_length=50)),
                ("bank_ifsc", models.CharField(max_length=20)),
                ("bank_account_holder", models.CharField(max_length=100)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_by", models.UUIDField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="accounts.vendorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_recharged",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "held_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("recharge", "Recharge"),
                            ("hold", "Hold"),
                            ("deduct", "Deduct"),
                            ("release", "Release"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_id", models.UUIDField(blank=True, null=True)),
                ("payment_gateway_ref", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.wallet",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
