# Generated by Django 5.2.4 on 2025-07-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_address_line2_address_landmark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="vendorkyc",
            name="rejection_reason",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vendorkyc",
            name="verified_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="kyc_approved_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="processed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
