# Generated by Django 4.2.23 on 2025-07-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_vendorprofile_gstin_vendorprofile_pan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorkyc",
            name="bank_account_holder",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vendorkyc",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vendorkyc",
            name="bank_ifsc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="vendorkyc",
            name="gstin_document",
            field=models.FileField(blank=True, null=True, upload_to="kyc/gstin/"),
        ),
        migrations.AlterField(
            model_name="vendorkyc",
            name="pan_document",
            field=models.FileField(blank=True, null=True, upload_to="kyc/pan/"),
        ),
    ]
