# Generated by Django 5.0 on 2025-08-12 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_vendorkyc_bank_account_holder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
