# Generated by Django 5.0 on 2025-08-12 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_wallet_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "verbose_name": "Buyer Wallet",
                "verbose_name_plural": "Buyer Wallets",
            },
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
