# Generated by Django 5.2.4 on 2025-08-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address_updates"),
        ("accounts", "0008_alter_wallet_options_alter_wallet_user"),
    ]

    operations = []
