# Generated by Django 5.2.4 on 2025-08-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_merge_20250816_1521"),
        ("products", "0002_add_location_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="vendors", to="products.location"
            ),
        ),
    ]
