# Generated by Django 5.2.4 on 2025-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_vendorprofile_locations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallettransaction",
            old_name="payment_gateway_ref",
            new_name="razorpay_payment_id",
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("recharge", "Recharge via Razorpay"),
                    ("hold", "Hold Amount for Order"),
                    ("deduct", "Deduct on Delivery"),
                    ("refund", "Refund to Wallet"),
                ],
                max_length=20,
            ),
        ),
    ]
