# Generated by Django 5.0 on 2025-08-12 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_wallet", "Can view wallet"),
                    ("can_manage_wallet", "Can manage wallet"),
                    ("add_money", "Can add money to wallet"),
                    ("withdraw_money", "Can withdraw money from wallet"),
                ],
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.AlterField(
            model_name="wallet",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Designates whether this wallet is active."
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                help_text="Only buyers can have wallets",
                limit_choices_to={"user_type": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
