# Generated by Django 5.0 on 2025-08-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycapproval",
            name="bank_account_holder",
            field=models.CharField(
                blank=True,
                help_text="Name of the account holder as per bank records",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kycapproval",
            name="bank_account_number",
            field=models.CharField(
                blank=True, help_text="Bank account number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="kycapproval",
            name="bank_ifsc",
            field=models.CharField(
                blank=True,
                help_text="IFSC code of the bank branch",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kycapproval",
            name="document_verification_notes",
            field=models.TextField(
                blank=True, help_text="Notes about document verification", null=True
            ),
        ),
        migrations.AddField(
            model_name="kycapproval",
            name="is_document_verified",
            field=models.BooleanField(
                default=False, help_text="Whether documents were properly verified"
            ),
        ),
    ]
